### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by tylrw** [ethanbayliss/infra-k8s#21]
👋 @ethanbayliss. Your project came up when searching EKS Blueprint implementations on GitHub.  
The Makefile looks pretty handy. Any chance you'll be adding a License?

I'm currently trying to figure out add-ons can be safely deployed with both the Terraform Helm provider and Argo CD.

**Comment by ethanbayliss** [comment]
Hi @rtwall

This is very much a work in progress and the current state does not completely work :(

Have a look at this if you want an example. https://innovate-modernapps-apj.virtual.awsevents.com/media/Fast%20track%20your%20Kubernetes%20adoption%20with%20Amazon%20EKS%20Blueprints/1_bjorid9i/274266122

The video above mentions the "argocd_manage_add_ons = true" flag which may be what you're looking for

I also used the examples from the blueprints repo, very handy for implementing this.
